"""gen_resolve_table.py -- WS-1.5 (GRADUATED_CONFORMANCE_PIPELINE_PLAN.md detail A2).

Emits a C++ header mapping D2Common function NAME -> VERIFIED runtime address,
from corrected_maps/D2Common.tsv (the ground-truth ordinal->address->ghidra_name).
The patch exposes it via D2MOO_ResolveGameFn(name) so a reimpl can resolve its
game dependencies by VERIFIED ADDRESS -- never by the scrambled export table
(ORDINAL_RECONCILIATION.md). This is the shared foundation for both the
MemoryModule custom import resolver and the dependency-injection fallback.

Run: python gen_resolve_table.py
Output: D2.Detours.patches/1.13c/D2Common_ResolveTable.gen.h
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
TSV = os.path.join(ROOT, "conformance", "corrected_maps", "D2Common.tsv")
OUT = os.path.join(ROOT, "D2.Detours.patches", "1.13c", "D2Common_ResolveTable.gen.h")


def main():
    rows = []
    seen = set()
    with open(TSV, encoding="utf-8") as f:
        next(f)  # header
        for line in f:
            p = line.rstrip("\n").split("\t")
            if len(p) < 3:
                continue
            addr, ghidra_name = p[1], p[2]
            if not ghidra_name or ghidra_name in seen:
                continue  # keep first occurrence of each name
            try:
                a = int(addr, 16)
            except ValueError:
                continue
            # only real code names (skip data ptrs / unnamed placeholders)
            if ghidra_name.startswith((";", "?", "-")) or " " in ghidra_name:
                continue
            seen.add(ghidra_name)
            rows.append((ghidra_name, a))

    # Curated DATA globals (name -> verified address). Ghidra data symbols aren't
    # in corrected_maps (which is function-oriented), so reimpls that read REAL
    # game globals BY NAME via the injected resolver (provider_runtime.h) get the
    # addresses from here. Extend as reimpls need more globals; verify each with
    # Ghidra list_globals. (Stateful rung 2 of GRADUATED_CONFORMANCE_PIPELINE_PLAN.)
    DATA_GLOBALS = {
        "g_dwDataTableBase": 0x6fdee2cc,  # bounded data-table base (GetDataTableRowEntryCount)
        "g_anTownLevelIds":  0x6fde4084,  # 5 act town level ids (DUNGEON_GetTownLevelIdFromActNo)
    }
    for name, a in DATA_GLOBALS.items():
        if name not in seen:
            seen.add(name)
            rows.append((name, a))

    rows.sort(key=lambda r: r[0])  # sorted by name for readability / future bsearch
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by conformance/tools/gen_resolve_table.py -- do not edit.\n")
        f.write("// D2Common function NAME -> VERIFIED absolute address (game D2Common @ 0x6fd50000).\n")
        f.write("// Source of truth: conformance/corrected_maps/D2Common.tsv (Ghidra names).\n")
        f.write("#pragma once\n\n")
        f.write("struct D2MOO_ResolveEntry { const char* name; unsigned int addr; };\n\n")
        f.write("static const D2MOO_ResolveEntry g_d2moo_resolve_table[] = {\n")
        for name, a in rows:
            f.write('\t{ "%s", 0x%xu },\n' % (name, a))
        f.write("};\n")
        f.write("static const int g_d2moo_resolve_count = %d;\n" % len(rows))

    print(f"Wrote {OUT} ({len(rows)} entries)")


if __name__ == "__main__":
    main()
