"""gen_provider_globals.py -- emit the provider-side SUPPLEMENTARY global table.

Why this exists
---------------
`D2MOO_ResolveGameFn` in the patch (D2.Detours.patches/1.13c/) linear-scans a
table that is baked in at COMPILE time. Activating a newly-wired global there
costs a patch rebuild + a full game restart + a character reload -- and the game
runs elevated, so that restart cannot be automated from an unprivileged worker.
That single constraint is what stalled the port pipeline for three days in July
2026: 87 candidates sat blocked behind globals that were "wired" on disk but not
present in the running process's baked table.

`D2MOO_Resolve` (provider_runtime.cpp), by contrast, lives in the provider --
which D2Debugger HOT-RELOADS on every prove. Emitting the same name->address
pairs into the provider lets a newly-wired global go live with a hot-reload
instead of a restart.

Ordering is deliberately ADDITIVE: provider_runtime.cpp asks the injected
resolver FIRST and only falls back to this table when that returns null. So this
file can add names the running patch has never heard of, but can never shadow a
verified one. Rebuilding the patch later is still correct -- it just stops being
urgent.

MODULE+RVA, NOT ABSOLUTE (2026-07-30)
-------------------------------------
Same rewrite as gen_resolve_table.py, and this is the leg that lands WITHOUT a
game restart: 3,392 of the 3,420 staged globals are D2Client-range, and D2Client
does not load at its Ghidra base (0x03600000 live vs 0x6fab0000 in Ghidra), so
every one of them resolved to unmapped memory. Entries are now (module, rva) and
provider_runtime.cpp adds the module's runtime base -- and because the provider
hot-reloads on every prove, regenerating this file fixes the globals immediately.

Run: python gen_provider_globals.py
Output: conformance/reimpl_provider/provider_globals.gen.h
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PENDING = os.path.join(HERE, "pending_globals.json")
OUT = os.path.join(ROOT, "conformance", "reimpl_provider", "provider_globals.gen.h")

# One attribution implementation, shared with the patch-side table -- two copies
# of "which module owns this address" is two chances to disagree, and a
# disagreement here is a silent bad pointer.
sys.path.insert(0, HERE)
from gen_resolve_table import (  # noqa: E402
    MODULE_RANGES,
    AttributionError as ModuleAttributionError,
    _module_for_address,
)

_GHIDRA_BASE = {m: lo for m, lo, _hi in MODULE_RANGES}


def main() -> int:
    rows = []
    if os.path.exists(PENDING):
        with open(PENDING, encoding="utf-8") as f:
            pending = json.load(f)
        for name, a in pending.items():
            addr = int(a, 0) if isinstance(a, str) else int(a)
            rows.append((name, addr))
    # provider_runtime.cpp BINARY-SEARCHES this table, so it must be in strcmp
    # (unsigned byte) order -- not Python's default str ordering, which only
    # coincides with it for pure ASCII.
    rows.sort(key=lambda r: r[0].encode("utf-8"))

    entries, failures = [], []
    for name, addr in rows:
        try:
            mod = _module_for_address(addr)
        except ModuleAttributionError as exc:
            failures.append(f"  {name}: {exc}")
            continue
        entries.append((name, mod, addr - _GHIDRA_BASE[mod]))
    if failures:
        print(f"[gen_provider_globals] FATAL: {len(failures)} address(es) could not "
              f"be attributed to a module:", file=sys.stderr)
        print("\n".join(failures[:40]), file=sys.stderr)
        if len(failures) > 40:
            print(f"  ... and {len(failures) - 40} more", file=sys.stderr)
        return 1

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by conformance/tools/gen_provider_globals.py -- do not edit.\n")
        f.write("// Supplementary NAME -> (MODULE, RVA) table, consulted ONLY when the\n")
        f.write("// injected D2MOO_ResolveGameFn returns null (see provider_runtime.cpp).\n")
        f.write("// provider_runtime.cpp adds the module's RUNTIME base, so an entry is correct\n")
        f.write("// even for a module that did not get its preferred base (D2Client).\n")
        f.write("// Source: conformance/tools/pending_globals.json\n")
        f.write("#pragma once\n\n")
        f.write("struct D2MOO_ProviderGlobal { const char* name; const char* module; unsigned int rva; };\n\n")
        f.write("static const D2MOO_ProviderGlobal g_d2moo_provider_globals[] = {\n")
        for name, mod, rva in entries:
            f.write('\t{ "%s", "%s", 0x%xu },\n' % (name, mod, rva))
        if not entries:
            f.write('\t{ nullptr, nullptr, 0u },\n')  # never an empty array
        f.write("};\n")
        f.write("static const int g_d2moo_provider_global_count = %d;\n" % len(entries))

    by_module = {}
    for _, mod, _r in entries:
        by_module[mod] = by_module.get(mod, 0) + 1
    print(f"Wrote {OUT} ({len(entries)} entries)")
    for mod, n in sorted(by_module.items(), key=lambda kv: -kv[1]):
        print(f"  {mod:<18} {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
