#!/usr/bin/env python3
"""Generate D2Common_ShadowDispatch.gen.h from shadow_manifest.json.

Full-D2Common 1:1 shadow-conformance (conformance/D2COMMON_FULL_SHADOW_PLAN.md):
each manifest entry becomes a live shadow dispatcher (atomic mode + Detours
trampoline slot + swappable reimpl ptr + typed Thunk) hooked by VERIFIED OFFSET.
Emits the dispatcher namespaces, the LiveDispatchGen bridge table + accessors
(the coord header's C exports delegate here), and Install(ctx) -- the
ApplyPatchAction calls placed in DllPreLoadHook.

Currently emits CLASS A (return-value integer, <=32-bit, comparison = masked
return value; reimpl pure or read-only-through-pointer). Other classes (void
out-param / mutation / register-explicit / u64) are future work; see the plan.

Usage:  python gen_shadow_dispatch.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MANIFEST = os.path.join(ROOT, "conformance", "shadow_manifest.json")
OUT = os.path.join(ROOT, "D2.Detours.patches", "1.13c", "D2Common_ShadowDispatch.gen.h")

CC = {"fastcall": "__fastcall", "stdcall": "__stdcall", "cdecl": "__cdecl"}


def ns_of(name):
    return name + "Dispatch"


def emit_dispatcher(e):
    name = e["name"]
    ns = ns_of(name)
    cc = CC[e["callconv"]]
    argc = len(e["args"])
    retbits = int(e.get("ret_bits", 32))
    params = ", ".join(f"uint32_t a{i}" for i in range(argc))
    argnames = ", ".join(f"a{i}" for i in range(argc))
    fnptr_args = ", ".join(["uint32_t"] * argc) if argc else ""
    if argc:
        av = "; ".join([f"const uint32_t av[] = {{ {argnames} }}"]) + ";"
        logcall = f'LiveDispatchGen::LogDivergence("{name}", av, {argc}, ro, rr);'
    else:
        av = ""
        logcall = f'LiveDispatchGen::LogDivergence("{name}", nullptr, 0, ro, rr);'
    return f"""// {name} -- class A (return-value integer, {e['callconv']}, {argc} arg(s), ret {retbits}-bit) -- off 0x{e['offset']:x}
namespace {ns} {{
	static std::atomic<int32_t> mode{{ (int32_t)LiveDispatchGen::Mode::Original }};
	static void* trampoline = nullptr;
	static uint64_t hits = 0, divergences = 0;
	static void* reimpl = nullptr;   // bound from the provider DLL BY NAME (D2Debugger)
	static uint32_t {cc} Thunk({params}) {{
		++hits;
		using Fn = uint32_t({cc}*)({fnptr_args});
		const Fn orig = (Fn)trampoline;
		const Fn rfn  = (Fn)reimpl;
		const LiveDispatchGen::Mode m = LiveDispatchGen::tl_inDispatch
			? LiveDispatchGen::Mode::Original
			: (LiveDispatchGen::Mode)mode.load(std::memory_order_relaxed);
		if (m == LiveDispatchGen::Mode::Reimpl && rfn) {{ LiveDispatchGen::Guard g; return rfn({argnames}); }}
		if (m != LiveDispatchGen::Mode::Shadow || !orig || !rfn) return orig ? orig({argnames}) : 0u;
		const uint32_t ro = orig({argnames});
		uint32_t rr;
		{{ LiveDispatchGen::Guard g; rr = rfn({argnames}); }}
		const uint32_t mask = LiveDispatchGen::RetMask({retbits});
		if ((ro & mask) != (rr & mask)) {{
			++divergences;
			{av}
			{logcall}
		}}
		return ro;
	}}
}}
"""


def emit(manifest):
    entries = manifest["entries"]
    parts = []
    parts.append("""#pragma once
// D2Common_ShadowDispatch.gen.h -- GENERATED by conformance/tools/gen_shadow_dispatch.py
// from conformance/shadow_manifest.json. DO NOT EDIT BY HAND; edit the manifest +
// regenerate. Full-D2Common 1:1 shadow-conformance (D2COMMON_FULL_SHADOW_PLAN.md).
//
// Include AFTER DetoursPatch.h (Install() uses HookContext/PatchAction) and after
// LiveDispatch_Generic.h. Single-TU home (D2Common.patch.cpp), same model as the
// coord header.
#include <cstdio>
#include "LiveDispatch_Generic.h"

// One-time shared definitions (declared extern in LiveDispatch_Generic.h).
namespace LiveDispatchGen {
	thread_local bool tl_inDispatch = false;
	std::atomic<int> g_inFlight{ 0 };
	static const char* kDivergencePath =
		"C:\\\\Users\\\\benam\\\\source\\\\cpp\\\\D2MOO\\\\conformance\\\\behavioral\\\\live_shadow_divergences.jsonl";
	void LogDivergence(const char* fn, const uint32_t* args, int nargs, uint32_t o, uint32_t r) {
		FILE* f = nullptr;
		if (fopen_s(&f, kDivergencePath, "a") == 0 && f) {
			fprintf(f, "{\\"fn\\":\\"%s\\",\\"args\\":[", fn);
			for (int i = 0; i < nargs; ++i) fprintf(f, "%s%u", i ? "," : "", args[i]);
			fprintf(f, "],\\"orig_ret\\":%u,\\"reimpl_ret\\":%u,\\"note\\":\\"live SHADOW divergence vs PD2-S12\\"}\\n", o, r);
			fclose(f);
		}
		char buf[256];
		_snprintf_s(buf, sizeof(buf), _TRUNCATE,
			"[LiveDispatchGen] SHADOW DIVERGENCE %s: orig=%u reimpl=%u\\n", fn, o, r);
		OutputDebugStringA(buf);
	}
}
""")
    for e in entries:
        parts.append(emit_dispatcher(e))

    # Bridge table + accessors.
    parts.append("namespace LiveDispatchGen {\n")
    if entries:
        parts.append("\tstatic GenEntry g_entries[] = {\n")
        for e in entries:
            ns = ns_of(e["name"])
            parts.append(
                f'\t\t{{ "{e["name"]}", 0x{e["offset"]:x}, &{ns}::mode, &{ns}::hits, '
                f'&{ns}::divergences, (void**)&{ns}::reimpl, &{ns}::trampoline }},\n')
        parts.append("\t};\n")
        parts.append("\tstatic const int kGenCount = (int)(sizeof(g_entries) / sizeof(g_entries[0]));\n")
    else:
        parts.append("\tstatic GenEntry* g_entries = nullptr;\n")
        parts.append("\tstatic const int kGenCount = 0;\n")
    parts.append("""	int Count() { return kGenCount; }
	const char* Name(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].name : ""; }
	uint32_t Offset(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].offset : 0xFFFFFFFFu; }
	int GetMode(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].mode->load(std::memory_order_relaxed) : 0; }
	void SetMode(int i, int m) { if (i >= 0 && i < kGenCount) g_entries[i].mode->store(m, std::memory_order_relaxed); }
	unsigned long long Hits(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].hits : 0ull; }
	unsigned long long Divergences(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].divergences : 0ull; }
	void* Trampoline(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].trampolineSlot : nullptr; }
	void* Reimpl(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].reimplSlot : nullptr; }
	void SetReimpl(int i, void* fn) { if (i >= 0 && i < kGenCount) *g_entries[i].reimplSlot = fn; }
	void QuiesceModes() { for (int i = 0; i < kGenCount; ++i) g_entries[i].mode->store(0, std::memory_order_seq_cst); }
	int InFlight() { return g_inFlight.load(std::memory_order_seq_cst); }
}
""")

    # Install -- ApplyPatchAction per entry (called from DllPreLoadHook).
    parts.append("namespace LiveDispatchGen {\n\tinline void Install(HookContext* ctx) {\n")
    for e in entries:
        ns = ns_of(e["name"])
        parts.append(
            f"\t\tctx->ApplyPatchAction(ctx, 0x{e['offset']:x}, (void*)&{ns}::Thunk, "
            f"PatchAction::FunctionReplaceOriginalByPatch, (void**)&{ns}::trampoline);\n")
    parts.append("\t}\n}\n")
    return "".join(parts)


def main():
    with open(MANIFEST, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    # normalize offset (accept hex string or int)
    for e in manifest["entries"]:
        if isinstance(e["offset"], str):
            e["offset"] = int(e["offset"], 0)
    text = emit(manifest)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"[gen_shadow_dispatch] wrote {OUT} ({len(manifest['entries'])} dispatcher(s))")
    for e in manifest["entries"]:
        print(f"    - {e['name']} @ 0x{e['offset']:x} ({e['callconv']}, class {e.get('class','A')})")


if __name__ == "__main__":
    main()
