#include <DetoursPatch.h>

#include <D2DataTbls.h>
#include <Drlg/D2DrlgPreset.h>
#include <Drlg/D2DrlgOutRoom.h>
#include <Drlg/D2DrlgRoomTile.h>
#include <Drlg/D2DrlgActivate.h>
#include <Drlg/D2DrlgOutdoors.h>
#include <Drlg/D2DrlgTileSub.h>
#include <Drlg/D2DrlgOutPlace.h>

//#define DISABLE_ALL_PATCHES

#if defined(__clang__)
#pragma clang diagnostic ignored "-Wmicrosoft-cast"
#endif

extern "C" {
    constexpr int __cdecl GetBaseOrdinal() { return 10'000; }
    constexpr int __cdecl GetLastOrdinal() { return 11'171; }
    constexpr int GetOrdinalCount() { return GetLastOrdinal() - GetBaseOrdinal() + 1; }
}

// We are using the following letters:
// /*C*/ to mean that the function has been "Checked" and works
// /*B*/ to mean wean know it is "Broken" and needs fixing.
//`     ` (spaces) to mean that it is "Unknown" wether it works or not
//
// NOTE: This is a starting template for 1.13c support.
// The ordinal-to-function mappings need to be verified against 1.13c binaries.
// For now, all functions default to FunctionReplacePatchByOriginal (safe).
// As functions are verified, they can be changed to FunctionReplaceOriginalByPatch.

static PatchAction patchActions[GetOrdinalCount()] = {
    // DRLG functions
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_GetLevelTypeFromLevelId                                        @10000
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_GetActNoFromLevelId                                            @10001
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_GetLOSDrawFromLevelId                                          @10002
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLGACTIVATE_Update                                                 @10003
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_GetSaveMonstersFromLevelId                                     @10004
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_GetLevel                                                       @10005
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_InitLevel                                                      @10006
    PatchAction::FunctionReplacePatchByOriginal,       //   DUNGEON_GetRoomExFromRoom                                           @10007
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLGPRESET_GetLevelPrestIdFromRoomEx                                @10008
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLGPRESET_GetPickedLevelPrestFilePathFromRoomEx                    @10009
    PatchAction::FunctionReplacePatchByOriginal,       //   DATATBLS_GetLevelDefRecord                                          @10010
    PatchAction::FunctionReplacePatchByOriginal,       //   DATATBLS_GetAutomapCellId                                           @10011
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_FreeDrlg                                                       @10012
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_AllocLevel                                                     @10013
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLG_AllocDrlg                                                      @10014
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLGACTIVATE_GetRoomsAllocationStats                                @10015
    PatchAction::FunctionReplacePatchByOriginal,       //   D2COMMON_10016_Return0                                              @10016
    PatchAction::FunctionReplacePatchByOriginal,       //   DRLGROOMTILE_GetNumberOfShadowsFromRoom                             @10017
    PatchAction::FunctionReplacePatchByOriginal,       //   D2COMMON_10018_Return0                                              @10018
    PatchAction::FunctionReplacePatchByOriginal,       //   D2COMMON_10019_Return                                               @10019
    // Remaining ordinals 10020-11171 filled with default action
    // This array needs 1172 entries total (10000-11171)
#define PATCH_DEFAULT PatchAction::FunctionReplacePatchByOriginal
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10020-10024
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10025-10029
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10030-10034
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10035-10039
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10040-10044
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10045-10049
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10050-10054
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10055-10059
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10060-10064
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10065-10069
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10070-10074
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10075-10079
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10080-10084
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10085-10089
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10090-10094
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, // 10095-10099
    // 10100-10199
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10200-10299
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10300-10399
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10400-10499
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10500-10599
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10600-10699
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10700-10799
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10800-10899
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 10900-10999
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 11000-11099
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    // 11100-11171
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT, PATCH_DEFAULT,
    PATCH_DEFAULT, PATCH_DEFAULT, // 11170, 11171
#undef PATCH_DEFAULT
};

extern "C" {

PatchAction __cdecl GetPatchAction(int ordinal)
{
#ifdef DISABLE_ALL_PATCHES
    return PatchAction::Ignore;
#else

    if (ordinal < GetBaseOrdinal() || ordinal > GetLastOrdinal())
        return PatchAction::FunctionReplacePatchByOriginal;

    static_assert(GetOrdinalCount() == (sizeof(patchActions) / sizeof(*patchActions)), "Make sure we have the right number of ordinal patch entries");
    return ::patchActions[ordinal - GetBaseOrdinal()];
#endif
}

static const int D2CommonImageBase = 0x6FD50000;

static ExtraPatchAction extraPatchActions[] = {
#ifdef D2_VERSION_113C
    // TODO: Add 1.13c-specific extra patches here
    // Addresses will differ from 1.10f - need to find the equivalent addresses in 1.13c
    // Example format:
    // { 0x???????? - D2CommonImageBase, &FunctionName, PatchAction::FunctionReplaceOriginalByPatch },
#endif
    { 0, 0, PatchAction::Ignore}, // Here because we need at least one element in the array
};

constexpr int __cdecl GetExtraPatchActionsCount() {
#ifdef DISABLE_ALL_PATCHES
    return 0;
#else
    return sizeof(extraPatchActions) / sizeof(ExtraPatchAction);
#endif
}

ExtraPatchAction* __cdecl GetExtraPatchAction(int index)
{
    return &extraPatchActions[index];
}

__declspec(dllexport)
PatchInformationFunctions __cdecl GetPatchInformationFunctions(const wchar_t* dllName)
{
	D2_MAYBE_UNUSED(dllName);
	return { &GetBaseOrdinal, &GetLastOrdinal, &GetPatchAction, &GetExtraPatchActionsCount, &GetExtraPatchAction };
}

}

#include <type_traits>
static_assert(std::is_same<decltype(GetBaseOrdinal)*, GetIntegerFunctionType>::value, "Ensure calling convention doesn't change");
static_assert(std::is_same<decltype(GetLastOrdinal)*, GetIntegerFunctionType>::value, "Ensure calling convention doesn't change");
static_assert(std::is_same<decltype(GetPatchAction)*, GetPatchActionType>::value, "Ensure calling convention doesn't change");


static_assert(std::is_same<decltype(GetExtraPatchActionsCount)*, GetIntegerFunctionType>::value, "Ensure calling convention doesn't change");
static_assert(std::is_same<decltype(GetExtraPatchAction)*, GetExtraPatchActionType>::value, "Ensure calling convention doesn't change");

static_assert(std::is_same<decltype(GetPatchInformationFunctions)*, GetPatchInformationFunctionsType>::value, "Ensure calling convention doesn't change");
