#pragma once
// SGD2FreeRes_ShadowDispatch.gen.h -- GENERATED by conformance/tools/gen_shadow_dispatch.py
// from the SGD2FreeRes.dll shadow manifest. DO NOT EDIT BY HAND; edit the manifest +
// regenerate. Full-D2Common 1:1 shadow-conformance (D2COMMON_FULL_SHADOW_PLAN.md).
//
// Include AFTER DetoursPatch.h (Install() uses HookContext/PatchAction) and after
// LiveDispatch_Generic.h. Single-TU home (SGD2FreeRes.patch.cpp),
// same model as the coord header.
#include <cstdio>
#include <cstring>
#include <cstdlib>
#include <mutex>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include "LiveDispatch_Generic.h"

// One-time shared definitions (declared extern in LiveDispatch_Generic.h).
namespace LiveDispatchGen {
	thread_local bool tl_inDispatch = false;
	std::atomic<int> g_inFlight{ 0 };

	// --- lazy arming -------------------------------------------------------
	// The reimpl provider is loaded on demand (POST /reimpl/reload), which
	// happens long after launch. A function that only runs during STARTUP has
	// therefore already fired by the time anything can arm it, so it can never
	// be compared. Measured 2026-08-05: SGD2FreeRes's Sgd2fr_D2Client_SetTileCullingBound fires
	// exactly twice per process, both during init, and stayed at hits=2 across a
	// world load, 46,000 frames and every arming attempt of a long session.
	//
	// Arming from DllPreLoadHook would be the obvious fix and is the WRONG one:
	// that hook runs inside LoadLibrary, holding the loader lock, and
	// ReloadProvider loads a DLL and quiesces threads. That is the classic
	// deadlock, and it would hang the game at startup with no oracle left to
	// diagnose it.
	//
	// So arm on the FIRST DISPATCHED CALL instead. By then LoadLibrary has
	// returned and the lock is released, and for a startup-fired function the
	// first call is precisely the moment the provider needs to be bound. Cost
	// after the first call is one relaxed atomic load, alongside the ++hits and
	// mode.load() every thunk already does.
	//
	// D2Debugger owns the provider and is loaded well before any patch that
	// needs arming (measured: D2Debugger at module index 60, SGD2FreeRes at
	// 78/79), so resolving it by name here is safe. If it is absent we simply
	// stay unarmed -- never a fault, never a retry storm.
	std::atomic<bool> g_armAttempted{ false };
	void EnsureArmed()
	{
		bool expected = false;
		if (!g_armAttempted.compare_exchange_strong(expected, true,
				std::memory_order_acq_rel))
			return;                       // already tried exactly once
		if (HMODULE h = GetModuleHandleA("D2Debugger.dll"))
			if (auto fn = (void(__cdecl*)())GetProcAddress(h, "D2Dbg_EnsureProviderLoaded"))
				fn();
	}
	static const char* kModuleName = "SGD2FreeRes.dll";
	static const char* kDivergencePath =
		"C:\\Users\\benam\\source\\cpp\\D2MOO\\conformance\\behavioral\\live_shadow_divergences.jsonl";
	static void WriteArgsJson(FILE* f, const uint32_t* args, int nargs) {
		fprintf(f, "\"args\":[");
		for (int i = 0; i < nargs; ++i) fprintf(f, "%s%u", i ? "," : "", args[i]);
		fprintf(f, "]");
	}
	// --- CONF_REGRESSION vector capture (opt-in) ----------------------------
	// Shadow mode already runs BOTH original and reimpl on every real call and
	// diffs them. On a MATCH that is a golden {real input -> real game output}
	// pair -- exactly an offline test vector. When the game is launched with
	// D2MOO_CAPTURE_VECTORS=1, matching calls record DISTINCT samples (first-seen,
	// capped per fn so a 100M-hit path costs a hash-set probe, not 100M lines) to
	// captured_vectors.jsonl. conformance/tools/capture_to_corpus.py folds those
	// into a CONF_REGRESSION corpus for the offline suite. Default OFF => zero
	// behavior/perf change for normal shadow proving.
	static const char* kCapturePath =
		"C:\\Users\\benam\\source\\cpp\\D2MOO\\conformance\\behavioral\\captured_vectors.jsonl";
	static bool CaptureEnabled() {
		static const bool on = [] {
			char b[8] = { 0 }; size_t n = 0;
			return getenv_s(&n, b, sizeof(b), "D2MOO_CAPTURE_VECTORS") == 0 && n > 0 && b[0] == '1';
		}();
		return on;
	}
	static uint64_t HashU32s(const uint32_t* a, int n) {
		uint64_t h = 1469598103934665603ull;   // FNV-1a
		for (int i = 0; i < n; ++i) { h ^= a[i]; h *= 1099511628211ull; }
		return h;
	}
	// First-seen distinct key per fn, capped -- a small golden set, not every hit.
	static bool CaptureNovel(const char* fn, uint64_t key) {
		static std::mutex mtx;
		static std::unordered_map<std::string, std::unordered_set<uint64_t>> seen;
		std::lock_guard<std::mutex> lk(mtx);
		auto& s = seen[fn];
		if (s.size() >= 64 || s.count(key)) return false;
		s.insert(key); return true;
	}
	// Return-value ABI (class A / class D): key on inputs, record ret.
	void LogMatch(const char* fn, const uint32_t* args, int nargs, uint32_t ret) {
		if (!CaptureEnabled() || nargs <= 0) return;   // no inputs => nothing to vary
		if (!CaptureNovel(fn, HashU32s(args, nargs))) return;
		FILE* f = nullptr;
		if (fopen_s(&f, kCapturePath, "a") == 0 && f) {
			fprintf(f, "{\"fn\":\"%s\",\"module\":\"%s\",", fn, kModuleName);
			WriteArgsJson(f, args, nargs);
			fprintf(f, ",\"ret\":%u,\"src\":\"real\",\"note\":\"live SHADOW match captured vs PD2-S12\"}\n", ret);
			fclose(f);
		}
	}
	// Out-param ABI (class B): key on inputs + output bytes, record the out buffer.
	void LogMatchBuf(const char* fn, const uint32_t* args, int nargs,
		const unsigned char* out, int nbytes) {
		if (!CaptureEnabled()) return;
		uint64_t key = HashU32s(args, nargs);
		for (int i = 0; i < nbytes; ++i) { key ^= out[i]; key *= 1099511628211ull; }
		if (!CaptureNovel(fn, key)) return;
		FILE* f = nullptr;
		if (fopen_s(&f, kCapturePath, "a") == 0 && f) {
			fprintf(f, "{\"fn\":\"%s\",\"module\":\"%s\",", fn, kModuleName);
			WriteArgsJson(f, args, nargs);
			fprintf(f, ",\"out\":\"");
			for (int i = 0; i < nbytes; ++i) fprintf(f, "%02x", out[i]);
			fprintf(f, "\",\"src\":\"real\",\"note\":\"live SHADOW match captured vs PD2-S12\"}\n");
			fclose(f);
		}
	}
	void LogDivergence(const char* fn, const uint32_t* args, int nargs, uint32_t o, uint32_t r) {
		FILE* f = nullptr;
		if (fopen_s(&f, kDivergencePath, "a") == 0 && f) {
			fprintf(f, "{\"fn\":\"%s\",\"module\":\"%s\",", fn, kModuleName);
			WriteArgsJson(f, args, nargs);
			fprintf(f, ",\"orig_ret\":%u,\"reimpl_ret\":%u,\"note\":\"live SHADOW divergence vs PD2-S12\"}\n", o, r);
			fclose(f);
		}
		char buf[256];
		_snprintf_s(buf, sizeof(buf), _TRUNCATE,
			"[LiveDispatchGen] SHADOW DIVERGENCE %s: orig=%u reimpl=%u\n", fn, o, r);
		OutputDebugStringA(buf);
	}
	void LogDivergenceBuf(const char* fn, const uint32_t* args, int nargs,
		const unsigned char* origOut, const unsigned char* reimplOut, int nbytes) {
		FILE* f = nullptr;
		if (fopen_s(&f, kDivergencePath, "a") == 0 && f) {
			fprintf(f, "{\"fn\":\"%s\",\"module\":\"%s\",", fn, kModuleName);
			WriteArgsJson(f, args, nargs);
			fprintf(f, ",\"orig_out\":\"");
			for (int i = 0; i < nbytes; ++i) fprintf(f, "%02x", origOut[i]);
			fprintf(f, "\",\"reimpl_out\":\"");
			for (int i = 0; i < nbytes; ++i) fprintf(f, "%02x", reimplOut[i]);
			fprintf(f, "\",\"note\":\"live SHADOW out-param divergence vs PD2-S12\"}\n");
			fclose(f);
		}
		OutputDebugStringA("[LiveDispatchGen] SHADOW OUT-PARAM DIVERGENCE (see live_shadow_divergences.jsonl)\n");
	}
	void LogFault(const char* fn) {
		FILE* f = nullptr;
		if (fopen_s(&f, kDivergencePath, "a") == 0 && f) {
			fprintf(f, "{\"fn\":\"%s\",\"module\":\"%s\",\"fault\":true,\"note\":\"reimpl ACCESS VIOLATION caught by shadow-thunk SEH; original used, game safe\"}\n", fn, kModuleName);
			fclose(f);
		}
		char buf[192];
		_snprintf_s(buf, sizeof(buf), _TRUNCATE,
			"[LiveDispatchGen] REIMPL FAULT (caught) %s -- see live_shadow_divergences.jsonl\n", fn);
		OutputDebugStringA(buf);
	}
}
// Sgd2fr_D2Client_SetTileCullingBound -- class B (void out-param, cdecl, out arg a0 = 36 bytes) -- off 0x1bcc0
namespace Sgd2fr_D2Client_SetTileCullingBoundDispatch {
	static std::atomic<int32_t> mode{ (int32_t)LiveDispatchGen::Mode::Shadow };
	static void* trampoline = nullptr;
	static uint64_t hits = 0, divergences = 0;
	static LiveDispatchGen::DistinctSampler distinct;   // distinct arg tuples seen in shadow
	static void* reimpl = nullptr;   // bound from the provider DLL BY NAME (D2Debugger)
	// SEH-isolated reimpl call (POD-only + __try/__except -> no C2712). A faulting
	// reimpl is caught here so a buggy reimpl can never crash the game.
	static void SafeReimpl(void* fn, uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4, int* faulted) {
		__try { ((void(__cdecl*)(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t))fn)(a0, a1, a2, a3, a4); }
		__except (EXCEPTION_EXECUTE_HANDLER) { *faulted = 1; }
	}
	static void __cdecl Thunk(uint32_t a0, uint32_t a1, uint32_t a2, uint32_t a3, uint32_t a4) {
		LiveDispatchGen::EnsureArmed();
		++hits;
		using Fn = void(__cdecl*)(uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
		const Fn orig = (Fn)trampoline;
		void* rfn = reimpl;
		const LiveDispatchGen::Mode m = LiveDispatchGen::tl_inDispatch
			? LiveDispatchGen::Mode::Original
			: (LiveDispatchGen::Mode)mode.load(std::memory_order_relaxed);
		if (m == LiveDispatchGen::Mode::Reimpl && rfn) {
			int f = 0;
			LiveDispatchGen::tl_inDispatch = true; ++LiveDispatchGen::g_inFlight;
			SafeReimpl(rfn, a0, a1, a2, a3, a4, &f);
			--LiveDispatchGen::g_inFlight; LiveDispatchGen::tl_inDispatch = false;
			if (f) { ++divergences; LiveDispatchGen::LogFault("Sgd2fr_D2Client_SetTileCullingBound"); if (orig) orig(a0, a1, a2, a3, a4); }
			return;
		}
		if (m != LiveDispatchGen::Mode::Shadow || !orig || !rfn) { if (orig) orig(a0, a1, a2, a3, a4); return; }
		// Shadow: snapshot the out-buffer's INPUT bytes, let ORIGINAL write the
		// game's buffer (it wins), then run reimpl on an INDEPENDENT copy of the
		// input and compare -- the game's memory is never double-mutated.
		unsigned char inbuf[36], origOut[36], local[36];
		memcpy(inbuf, (const void*)(uintptr_t)a0, 36);
		orig(a0, a1, a2, a3, a4);
		memcpy(origOut, (const void*)(uintptr_t)a0, 36);
		memcpy(local, inbuf, 36);
		int f = 0;
		LiveDispatchGen::tl_inDispatch = true; ++LiveDispatchGen::g_inFlight;
		SafeReimpl(rfn, (uint32_t)(uintptr_t)local, a1, a2, a3, a4, &f);
		--LiveDispatchGen::g_inFlight; LiveDispatchGen::tl_inDispatch = false;
		const uint32_t av[] = { a0, a1, a2, a3, a4 };
		LiveDispatchGen::NoteInputs(distinct, av, 5);
		if (f) { ++divergences; LiveDispatchGen::LogFault("Sgd2fr_D2Client_SetTileCullingBound"); }
		else if (memcmp(local, origOut, 36) != 0) {
			++divergences;
			LiveDispatchGen::LogDivergenceBuf("Sgd2fr_D2Client_SetTileCullingBound", av, 5, origOut, local, 36);
		}
		else { LiveDispatchGen::LogMatchBuf("Sgd2fr_D2Client_SetTileCullingBound", av, 5, origOut, 36); }
	}
}
namespace LiveDispatchGen {
	static GenEntry g_entries[] = {
		{ "Sgd2fr_D2Client_SetTileCullingBound", 0x1bcc0, &Sgd2fr_D2Client_SetTileCullingBoundDispatch::mode, &Sgd2fr_D2Client_SetTileCullingBoundDispatch::hits, &Sgd2fr_D2Client_SetTileCullingBoundDispatch::divergences, (void**)&Sgd2fr_D2Client_SetTileCullingBoundDispatch::reimpl, &Sgd2fr_D2Client_SetTileCullingBoundDispatch::trampoline, &Sgd2fr_D2Client_SetTileCullingBoundDispatch::distinct, 5 },
	};
	static const int kGenCount = (int)(sizeof(g_entries) / sizeof(g_entries[0]));
	int Count() { return kGenCount; }
	const char* Name(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].name : ""; }
	uint32_t Offset(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].offset : 0xFFFFFFFFu; }
	int GetMode(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].mode->load(std::memory_order_relaxed) : 0; }
	void SetMode(int i, int m) { if (i >= 0 && i < kGenCount) g_entries[i].mode->store(m, std::memory_order_relaxed); }
	unsigned long long Hits(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].hits : 0ull; }
	unsigned long long DistinctInputs(int i) { return (i >= 0 && i < kGenCount)
		? (unsigned long long)g_entries[i].distinct->count.load(std::memory_order_relaxed) : 0ull; }
	int ArgCount(int i) { return (i >= 0 && i < kGenCount) ? g_entries[i].argc : -1; }
	// which: 0 = arg0, 1 = arg1, 2 = the slot's hash (0 == slot unused).
	// The slot array is SPARSE -- hashes land wherever they probe to -- so a
	// caller must sweep all kSlots and use which==2 to tell occupied from
	// empty. Iterating 0..DistinctInputs()-1 would read unwritten slots.
	uint32_t SampleValue(int i, int slot, int which) {
		if (i < 0 || i >= kGenCount) return 0u;
		if (slot < 0 || (uint32_t)slot >= DistinctSampler::kSlots) return 0u;
		DistinctSampler& s = *g_entries[i].distinct;
		if (which == 2) return s.slots[slot].load(std::memory_order_acquire);
		if (which == 1) return s.v1[slot].load(std::memory_order_relaxed);
		return s.v0[slot].load(std::memory_order_relaxed);
	}
	int SampleSlotCount() { return (int)DistinctSampler::kSlots; }
	unsigned long long Divergences(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].divergences : 0ull; }
	void* Trampoline(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].trampolineSlot : nullptr; }
	void* Reimpl(int i) { return (i >= 0 && i < kGenCount) ? *g_entries[i].reimplSlot : nullptr; }
	void SetReimpl(int i, void* fn) { if (i >= 0 && i < kGenCount) *g_entries[i].reimplSlot = fn; }
	void QuiesceModes() { for (int i = 0; i < kGenCount; ++i) g_entries[i].mode->store(0, std::memory_order_seq_cst); }
	int InFlight() { return g_inFlight.load(std::memory_order_seq_cst); }
}
namespace LiveDispatchGen {
	inline void Install(HookContext* ctx) {
		ctx->ApplyPatchAction(ctx, 0x1bcc0, (void*)&Sgd2fr_D2Client_SetTileCullingBoundDispatch::Thunk, PatchAction::FunctionReplaceOriginalByPatch, (void**)&Sgd2fr_D2Client_SetTileCullingBoundDispatch::trampoline);
	}
}

// --- D2MOO_LiveDispatch_* bridge exports (standalone: no coord family) ---
// Same shape as LiveDispatch_CoordFamily.h's block, unindexed. D2Debugger's
// multi-bridge ResolveBridge() collects every module exporting GetCount into
// its own slice of the global dispatcher index space.
extern "C" {
	__declspec(dllexport) int __cdecl D2MOO_LiveDispatch_GetCount()
	{
		return LiveDispatchGen::Count();
	}
	__declspec(dllexport) const char* __cdecl D2MOO_LiveDispatch_GetName(int i)
	{
		return LiveDispatchGen::Name(i);
	}
	__declspec(dllexport) unsigned int __cdecl D2MOO_LiveDispatch_GetOffset(int i)
	{
		return LiveDispatchGen::Offset(i);
	}
	__declspec(dllexport) int __cdecl D2MOO_LiveDispatch_GetMode(int i)
	{
		return LiveDispatchGen::GetMode(i);
	}
	__declspec(dllexport) void __cdecl D2MOO_LiveDispatch_SetMode(int i, int m)
	{
		LiveDispatchGen::SetMode(i, m);
	}
	__declspec(dllexport) unsigned long long __cdecl D2MOO_LiveDispatch_GetHits(int i)
	{
		return LiveDispatchGen::Hits(i);
	}
	__declspec(dllexport) unsigned long long __cdecl D2MOO_LiveDispatch_GetDivergences(int i)
	{
		return LiveDispatchGen::Divergences(i);
	}
	// input diversity (SHIPPING_PROMOTION_PLAN.md) -- battletest_promoter fails
	// closed without these, so an older build here correctly stalls promotion
	// for this module rather than promoting on volume alone.
	__declspec(dllexport) unsigned long long __cdecl D2MOO_LiveDispatch_GetDistinctInputs(int i)
	{
		return LiveDispatchGen::DistinctInputs(i);
	}
	__declspec(dllexport) int __cdecl D2MOO_LiveDispatch_GetArgCount(int i)
	{
		return LiveDispatchGen::ArgCount(i);
	}
	// Recorded input VALUES, so coverage guidance can name the ids already seen
	// instead of guessing at an activity. which: 0=arg0, 1=arg1, 2=slot hash
	// (0 == unused). Sweep slot in [0, GetSampleSlotCount()).
	__declspec(dllexport) unsigned int __cdecl D2MOO_LiveDispatch_GetSampleValue(
		int i, int slot, int which)
	{
		return LiveDispatchGen::SampleValue(i, slot, which);
	}
	__declspec(dllexport) int __cdecl D2MOO_LiveDispatch_GetSampleSlotCount(void)
	{
		return LiveDispatchGen::SampleSlotCount();
	}
	// WS-5 direct-call oracle support: raw original + currently-bound reimpl.
	__declspec(dllexport) void* __cdecl D2MOO_LiveDispatch_GetTrampoline(int i)
	{
		return LiveDispatchGen::Trampoline(i);
	}
	__declspec(dllexport) void* __cdecl D2MOO_LiveDispatch_GetReimpl(int i)
	{
		return LiveDispatchGen::Reimpl(i);
	}
	// WS-1 hot-reload bridge: repoint dispatcher i's reimpl to a function from
	// the (re)loaded provider DLL. Call ONLY between QuiesceForReload() and
	// re-enabling modes (D2Debugger's ReloadProvider already does this across
	// EVERY resolved module, this one included).
	__declspec(dllexport) void __cdecl D2MOO_LiveDispatch_SetReimpl(int i, void* fn)
	{
		LiveDispatchGen::SetReimpl(i, fn);
	}
	// Quiesce for a provider hot-reload: force every dispatcher to Original,
	// then wait for in-flight reimpl calls to drain (own drain counter -- no
	// coord family to share LiveDispatch::g_reimplInFlight with here). Mirrors
	// the coord family's exact (lenient) semantics: fast path on InFlight==0,
	// else a grace period once every mode is already Original (no NEW reimpl
	// call can start; an in-flight one finishes in microseconds), so this
	// ALWAYS eventually returns 1 -- never signals failure. Matching that is
	// required: D2Debugger's ReloadProvider treats `quiesce() != 1` as fatal
	// and aborts the reload for every resolved module.
	__declspec(dllexport) int __cdecl D2MOO_LiveDispatch_QuiesceForReload()
	{
		LiveDispatchGen::QuiesceModes();
		const int kGraceMs = 300;
		for (int spin = 0; spin < 5000; ++spin)
		{
			if (LiveDispatchGen::InFlight() == 0) return 1;
			if (spin >= kGraceMs) return 1;
			Sleep(1);
		}
		return 1;
	}
}
