// ============================================================================
//  PD2S12Conformance.gen.cpp -- GENERATED by conformance/tools/gen_offline_tests.py
//  DO NOT EDIT BY HAND. Edit the frozen corpora in conformance/regression/*.cases.json
//  and re-run the generator.
//
//  CONF_REGRESSION tier: replays 59 frozen {input -> real-game-output}
//  cases across 6 function(s) against D2MOO's REAL compiled D2Common,
//  entirely offline (no running game). A failure is a regression -- a code change
//  that made a proven function diverge from the captured ground truth.
// ============================================================================
#if defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable: 4820)  // padding added after struct member -- irrelevant for test tables
#pragma warning(disable: 4242 4244 4365)  // narrowing when a corpus int feeds a narrow param (uint8_t etc.)
#endif
#include <doctest.h>
#include <cstdint>

#include "D2Dungeon.h"

// ==== coord_family.cases.json (frozen 2026-07-07, PD2-S12 (1.13c) live oracle via D2Debugger :8790 /call -- original-DLL ground truth) ====
// DUNGEON_GameTileToClientCoords: 14 frozen cases (10 real, 4 synthetic)
TEST_CASE("CONF_REGRESSION: DUNGEON_GameTileToClientCoords [coord2] (10 real + 4 synthetic)")
{
	struct { int x, y, ex, ey; } cases[] = {
		{ 0, 0, 0, 0 },
		{ 1, 0, 80, 40 },
		{ 0, 1, -80, 40 },
		{ 5, 3, 160, 320 },
		{ 10, -4, 1120, 240 },
		{ -7, 2, -720, -200 },
		{ 1, 1, 0, 80 },
		{ 3, 7, -320, 400 },
		{ -2, 4, -480, 80 },
		{ 100, 20, 6400, 4800 },
		{ 32767, -32768, 5242800, -40 },
		{ -32768, 32767, -5242800, -40 },
		{ 2000, -2000, 320000, 0 },
		{ 999, -999, 159840, 0 },
	};
	for (auto& c : cases)
	{
		int x = c.x, y = c.y;
		DUNGEON_GameTileToClientCoords(&x, &y);
		CHECK(x == c.ex);
		CHECK(y == c.ey);
	}
}

// DUNGEON_GameTileToSubtileCoords: 10 frozen cases (7 real, 3 synthetic)
TEST_CASE("CONF_REGRESSION: DUNGEON_GameTileToSubtileCoords [coord2] (7 real + 3 synthetic)")
{
	struct { int x, y, ex, ey; } cases[] = {
		{ 0, 0, 0, 0 },
		{ 1, 0, 5, 0 },
		{ 0, 1, 0, 5 },
		{ 5, 3, 25, 15 },
		{ 3, 7, 15, 35 },
		{ -2, 4, -10, 20 },
		{ 100, 20, 500, 100 },
		{ 32767, -32768, 163835, -163840 },
		{ -32768, 32767, -163840, 163835 },
		{ -1, -2, -5, -10 },
	};
	for (auto& c : cases)
	{
		int x = c.x, y = c.y;
		DUNGEON_GameTileToSubtileCoords(&x, &y);
		CHECK(x == c.ex);
		CHECK(y == c.ey);
	}
}

// DUNGEON_ClientToGameCoords: 10 frozen cases (7 real, 3 synthetic)
TEST_CASE("CONF_REGRESSION: DUNGEON_ClientToGameCoords [coord2] (7 real + 3 synthetic)")
{
	struct { int x, y, ex, ey; } cases[] = {
		{ 0, 0, 0, 0 },
		{ 1, 0, 1, -1 },
		{ 0, 1, 2, 2 },
		{ 5, 3, 11, 1 },
		{ 10, -4, 2, -18 },
		{ -7, 2, -3, 11 },
		{ 100, 20, 140, -60 },
		{ 32767, -32768, -32769, -98303 },
		{ -32768, 32767, 32766, 98302 },
		{ -1, -2, -5, -3 },
	};
	for (auto& c : cases)
	{
		int x = c.x, y = c.y;
		DUNGEON_ClientToGameCoords(&x, &y);
		CHECK(x == c.ex);
		CHECK(y == c.ey);
	}
}

// DUNGEON_GameToClientCoords: 11 frozen cases (4 real, 7 synthetic)
TEST_CASE("CONF_REGRESSION: DUNGEON_GameToClientCoords [coord2] (4 real + 7 synthetic)")
{
	struct { int x, y, ex, ey; } cases[] = {
		{ 0, 0, 0, 0 },
		{ 8, 4, 2, 3 },
		{ 10, 2, 4, 3 },
		{ 100, 20, 40, 30 },
		{ 0, 3, -2, 0 },
		{ 1, 2, -1, 0 },
		{ 5, 10, -3, 3 },
		{ -1, -2, 0, -1 },
		{ 0, 1, -1, 0 },
		{ 32767, -32768, 32767, -1 },
		{ -32768, 32767, -32768, -1 },
	};
	for (auto& c : cases)
	{
		int x = c.x, y = c.y;
		DUNGEON_GameToClientCoords(&x, &y);
		CHECK(x == c.ex);
		CHECK(y == c.ey);
	}
}

// DUNGEON_GameSubtileToClientCoords: 9 frozen cases (6 real, 3 synthetic)
TEST_CASE("CONF_REGRESSION: DUNGEON_GameSubtileToClientCoords [coord2] (6 real + 3 synthetic)")
{
	struct { int x, y, ex, ey; } cases[] = {
		{ 0, 0, 0, 0 },
		{ 1, 0, 16, 8 },
		{ 0, 1, -16, 8 },
		{ 5, 3, 32, 64 },
		{ -2, 4, -96, 16 },
		{ 100, 20, 1280, 960 },
		{ 32767, -32768, 1048560, -8 },
		{ -32768, 32767, -1048560, -8 },
		{ -1, -2, 16, -24 },
	};
	for (auto& c : cases)
	{
		int x = c.x, y = c.y;
		DUNGEON_GameSubtileToClientCoords(&x, &y);
		CHECK(x == c.ex);
		CHECK(y == c.ey);
	}
}

// ==== town_levelid.cases.json (frozen 2026-07-07, PD2-S12 (1.13c) live oracle via D2Debugger :8790 /oracle -- original-DLL ground truth) ====
// DUNGEON_GetTownLevelIdFromActNo(nAct): 5 frozen cases (5 real, 0 synthetic)
TEST_CASE("CONF_REGRESSION: DUNGEON_GetTownLevelIdFromActNo [scalar_ret] (5 real + 0 synthetic)")
{
	struct { long long a0; long long ret; } cases[] = {
		{ 0LL, 1LL },
		{ 1LL, 40LL },
		{ 2LL, 75LL },
		{ 3LL, 103LL },
		{ 4LL, 109LL },
	};
	for (auto& c : cases)
		CHECK((long long)DUNGEON_GetTownLevelIdFromActNo(c.a0) == c.ret);
}

#if defined(_MSC_VER)
#pragma warning(pop)
#endif
